name: NodeJS Fastify API

run-name: Deploy to Ubuntu Server by @${{ github.actor }} 

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.18.2]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.IP }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ${{ secrets.APP_PATH }}
            sudo git pull origin
            npm install
            npm run migrate:up
            pm2 restart ${{ secrets.APP_ID }}
